package com.shung.pojo;

import org.springframework.stereotype.Component;

import java.math.BigDecimal;

@Component
public class Book {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.b_id
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    private Integer bId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.b_name
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    private String bName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.b_author
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    private String bAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.b_price
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    private BigDecimal bPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.b_sales
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    private Integer bSales;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.b_stoke
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    private Integer bStoke;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.b_imgPath
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    private String bImgpath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.b_id
     *
     * @return the value of t_book.b_id
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    public Integer getbId() {
        return bId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.b_id
     *
     * @param bId the value for t_book.b_id
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    public void setbId(Integer bId) {
        this.bId = bId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.b_name
     *
     * @return the value of t_book.b_name
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    public String getbName() {
        return bName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.b_name
     *
     * @param bName the value for t_book.b_name
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    public void setbName(String bName) {
        this.bName = bName == null ? null : bName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.b_author
     *
     * @return the value of t_book.b_author
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    public String getbAuthor() {
        return bAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.b_author
     *
     * @param bAuthor the value for t_book.b_author
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    public void setbAuthor(String bAuthor) {
        this.bAuthor = bAuthor == null ? null : bAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.b_price
     *
     * @return the value of t_book.b_price
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    public BigDecimal getbPrice() {
        return bPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.b_price
     *
     * @param bPrice the value for t_book.b_price
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    public void setbPrice(BigDecimal bPrice) {
        this.bPrice = bPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.b_sales
     *
     * @return the value of t_book.b_sales
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    public Integer getbSales() {
        return bSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.b_sales
     *
     * @param bSales the value for t_book.b_sales
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    public void setbSales(Integer bSales) {
        this.bSales = bSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.b_stoke
     *
     * @return the value of t_book.b_stoke
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    public Integer getbStoke() {
        return bStoke;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.b_stoke
     *
     * @param bStoke the value for t_book.b_stoke
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    public void setbStoke(Integer bStoke) {
        this.bStoke = bStoke;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.b_imgPath
     *
     * @return the value of t_book.b_imgPath
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    public String getbImgpath() {
        return bImgpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.b_imgPath
     *
     * @param bImgpath the value for t_book.b_imgPath
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    public void setbImgpath(String bImgpath) {
        this.bImgpath = bImgpath == null ? null : bImgpath.trim();
    }
}