package com.shung.pojo;

import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.util.Date;

@Component
public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_id
     *
     * @mbggenerated Sun Mar 12 00:34:38 CST 2023
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.createtime
     *
     * @mbggenerated Sun Mar 12 00:34:38 CST 2023
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.price
     *
     * @mbggenerated Sun Mar 12 00:34:38 CST 2023
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.status
     *
     * @mbggenerated Sun Mar 12 00:34:38 CST 2023
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.u_id
     *
     * @mbggenerated Sun Mar 12 00:34:38 CST 2023
     */
    private Integer uId;

    public Order() {
    }

    public Order(String orderId, Date createtime, BigDecimal price, Integer status, Integer uId) {
        this.orderId = orderId;
        this.createtime = createtime;
        this.price = price;
        this.status = status;
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_id
     *
     * @return the value of t_order.order_id
     *
     * @mbggenerated Sun Mar 12 00:34:38 CST 2023
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_id
     *
     * @param orderId the value for t_order.order_id
     *
     * @mbggenerated Sun Mar 12 00:34:38 CST 2023
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.createtime
     *
     * @return the value of t_order.createtime
     *
     * @mbggenerated Sun Mar 12 00:34:38 CST 2023
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.createtime
     *
     * @param createtime the value for t_order.createtime
     *
     * @mbggenerated Sun Mar 12 00:34:38 CST 2023
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.price
     *
     * @return the value of t_order.price
     *
     * @mbggenerated Sun Mar 12 00:34:38 CST 2023
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.price
     *
     * @param price the value for t_order.price
     *
     * @mbggenerated Sun Mar 12 00:34:38 CST 2023
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.status
     *
     * @return the value of t_order.status
     *
     * @mbggenerated Sun Mar 12 00:34:38 CST 2023
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.status
     *
     * @param status the value for t_order.status
     *
     * @mbggenerated Sun Mar 12 00:34:38 CST 2023
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.u_id
     *
     * @return the value of t_order.u_id
     *
     * @mbggenerated Sun Mar 12 00:34:38 CST 2023
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.u_id
     *
     * @param uId the value for t_order.u_id
     *
     * @mbggenerated Sun Mar 12 00:34:38 CST 2023
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }
}