package com.shung.pojo;

import org.springframework.stereotype.Component;

import java.math.BigDecimal;

@Component
public class OrderItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.id
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.orderId
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    private String orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.name
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.count
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.price
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.totalPrice
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    private BigDecimal totalprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.imgPath
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    private String imgpath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.id
     *
     * @return the value of t_order_item.id
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.id
     *
     * @param id the value for t_order_item.id
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.orderId
     *
     * @return the value of t_order_item.orderId
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.orderId
     *
     * @param orderid the value for t_order_item.orderId
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.name
     *
     * @return the value of t_order_item.name
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.name
     *
     * @param name the value for t_order_item.name
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.count
     *
     * @return the value of t_order_item.count
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.count
     *
     * @param count the value for t_order_item.count
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.price
     *
     * @return the value of t_order_item.price
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.price
     *
     * @param price the value for t_order_item.price
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.totalPrice
     *
     * @return the value of t_order_item.totalPrice
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    public BigDecimal getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.totalPrice
     *
     * @param totalprice the value for t_order_item.totalPrice
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    public void setTotalprice(BigDecimal totalprice) {
        this.totalprice = totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.imgPath
     *
     * @return the value of t_order_item.imgPath
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    public String getImgpath() {
        return imgpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.imgPath
     *
     * @param imgpath the value for t_order_item.imgPath
     *
     * @mbggenerated Sat Feb 25 01:45:50 CST 2023
     */
    public void setImgpath(String imgpath) {
        this.imgpath = imgpath == null ? null : imgpath.trim();
    }
}