package com.shung.pojo;

import org.springframework.stereotype.Component;

import java.math.BigDecimal;
@Component
public class OrderItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderitem.orderitem_id
     *
     * @mbggenerated Thu Mar 09 23:21:31 CST 2023
     */
    private Integer orderitemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderitem.order_id
     *
     * @mbggenerated Thu Mar 09 23:21:31 CST 2023
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderitem.name
     *
     * @mbggenerated Thu Mar 09 23:21:31 CST 2023
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderitem.count
     *
     * @mbggenerated Thu Mar 09 23:21:31 CST 2023
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderitem.price
     *
     * @mbggenerated Thu Mar 09 23:21:31 CST 2023
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderitem.total_price
     *
     * @mbggenerated Thu Mar 09 23:21:31 CST 2023
     */
    private BigDecimal totalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderitem.img_path
     *
     * @mbggenerated Thu Mar 09 23:21:31 CST 2023
     */
    private String imgPath;

    public OrderItem() {
    }

    public OrderItem(Integer orderitemId, String orderId, String name, Integer count, BigDecimal price, BigDecimal totalPrice, String imgPath) {
        this.orderitemId = orderitemId;
        this.orderId = orderId;
        this.name = name;
        this.count = count;
        this.price = price;
        this.totalPrice = totalPrice;
        this.imgPath = imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderitem.orderitem_id
     *
     * @return the value of t_orderitem.orderitem_id
     *
     * @mbggenerated Thu Mar 09 23:21:31 CST 2023
     */
    public Integer getOrderitemId() {
        return orderitemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderitem.orderitem_id
     *
     * @param orderitemId the value for t_orderitem.orderitem_id
     *
     * @mbggenerated Thu Mar 09 23:21:31 CST 2023
     */
    public void setOrderitemId(Integer orderitemId) {
        this.orderitemId = orderitemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderitem.order_id
     *
     * @return the value of t_orderitem.order_id
     *
     * @mbggenerated Thu Mar 09 23:21:31 CST 2023
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderitem.order_id
     *
     * @param orderId the value for t_orderitem.order_id
     *
     * @mbggenerated Thu Mar 09 23:21:31 CST 2023
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderitem.name
     *
     * @return the value of t_orderitem.name
     *
     * @mbggenerated Thu Mar 09 23:21:31 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderitem.name
     *
     * @param name the value for t_orderitem.name
     *
     * @mbggenerated Thu Mar 09 23:21:31 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderitem.count
     *
     * @return the value of t_orderitem.count
     *
     * @mbggenerated Thu Mar 09 23:21:31 CST 2023
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderitem.count
     *
     * @param count the value for t_orderitem.count
     *
     * @mbggenerated Thu Mar 09 23:21:31 CST 2023
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderitem.price
     *
     * @return the value of t_orderitem.price
     *
     * @mbggenerated Thu Mar 09 23:21:31 CST 2023
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderitem.price
     *
     * @param price the value for t_orderitem.price
     *
     * @mbggenerated Thu Mar 09 23:21:31 CST 2023
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderitem.total_price
     *
     * @return the value of t_orderitem.total_price
     *
     * @mbggenerated Thu Mar 09 23:21:31 CST 2023
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderitem.total_price
     *
     * @param totalPrice the value for t_orderitem.total_price
     *
     * @mbggenerated Thu Mar 09 23:21:31 CST 2023
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderitem.img_path
     *
     * @return the value of t_orderitem.img_path
     *
     * @mbggenerated Thu Mar 09 23:21:31 CST 2023
     */
    public String getImgPath() {
        return imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderitem.img_path
     *
     * @param imgPath the value for t_orderitem.img_path
     *
     * @mbggenerated Thu Mar 09 23:21:31 CST 2023
     */
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath == null ? null : imgPath.trim();
    }
}